# Arquivo de override para desenvolvimento
# Este arquivo é usado automaticamente pelo docker-compose
# para configurações específicas de desenvolvimento

services:
  app:
    volumes:
      # Adicionar volume para hot reload em desenvolvimento
      - ./:/var/www/html
      # Volume para logs
      - ./storage/logs:/var/www/html/storage/logs
    environment:
      # Configurações específicas para desenvolvimento
      - APP_DEBUG=true
      - LOG_LEVEL=debug
      - TELESCOPE_ENABLED=true
    # Comando para desenvolvimento com hot reload
    command: >
      sh -c "
        php artisan serve --host=0.0.0.0 --port=8000 &
        php artisan queue:work --verbose --tries=3 --timeout=90 &
        wait
      "

  db:
    # Configurações específicas para desenvolvimento
    environment:
      - POSTGRES_DB=alfred_db
      - POSTGRES_USER=alfred_user
      - POSTGRES_PASSWORD=alfred_password
    # Volume para persistir dados do banco
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

  redis:
    # Configurações específicas para desenvolvimento
    command: redis-server --appendonly yes
    volumes:
      - redis_dev_data:/data

volumes:
  postgres_dev_data:
  redis_dev_data:
